#
backend:
  name: git-gateway
  branch: master

media_folder: 'public/img/uploads'
public_folder: '/img/uploads'

collections:

  # static content for pages
  # may vary by template

  - name: 'pages'
    label: 'Páginas'
    delete: false
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/pages/home.json'
        fields:
          - label: "Slider"
            name: "carousel"
            widget: object
            fields:
              - label: Images
                name: images
                widget: list
                fields:
                  - {label: Imagem, required: false, name: image, widget: image}
                  - {label: Alt, required: false, name: Alt tag, widget: string}
          - name: 'showcase'
            label: 'Vitrine'
            widget: object
            fields:
              - label: "Product box style"
                name: "product_box_style"
                widget: "select"
                options: ["Default", "Quickview", "Sidebar"]
              - {label: Collection, required: false, name: collection, widget: string}
          - label: "Botton infos"
            name: "botton_infos"
            widget: object
            fields:
              - label: Left info
                name: left_info
                widget: object
                fields:
                  - {label: Title, required: false, name: title, widget: string}
                  - {label: Description, required: false, name: description, widget: string}
                  - {label: Link text, required: false, name: link_text, widget: string}
                  - {label: Link url, required: false, name: link_url, widget: string}
              - label: Right info
                name: right_info
                widget: object
                fields:
                  - {label: Title, required: false, name: title, widget: string}
                  - {label: Description, required: false, name: description, widget: string}
                  - {label: Link text, required: false, name: link_text, widget: string}
                  - {label: Link url, required: false, name: link_url, widget: string}
      - name: '_product'
        label: 'Product page'
        file: 'content/pages/_product.json'
        fields:
          - name: 'product_box'
            label: 'Product box'
            widget: object
            fields:
              - label: "Product box style"
                name: "product_box_style"
                widget: "select"
                options: ["Default", "Description on sidebar acordion", "Project"]
          - {label: 'Body', name: 'body', widget: 'markdown'}
      - name: '_about'
        label: 'About us page'
        file: 'content/pages/_about.json'
        fields:
          - label: "Content style"
            name: "content_style"
            widget: "select"
            options: ["Image on side", "Image first"]
          - label: Image
            name: image
            widget: object
            fields:
              - {label: Image, required: false, name: image, widget: image}
              - {label: alt, required: false, name: Alt tag, widget: string}
          - {label: 'Body', required: false, name: 'body', widget: 'markdown'}
      - name: '_blog'
        label: 'Blog page'
        file: 'content/pages/_blog.json'
        fields:
          - {label: 'Body', required: false, name: 'body', widget: 'markdown'}
          - name: 'posts_box'
            label: 'Posts box'
            widget: object
            fields:
              - label: "Posts box style"
                name: "post_box_style"
                required: false
                widget: "select"
                options: ["Big tumbnail", "Grid", "List", "Two per row"]
      - name: '_faq'
        label: 'FAQ page'
        file: 'content/pages/_faq.json'
        fields:
          - label: "FAQs"
            name: "faqs"
            widget: object
            fields:
              - label: "Style"
                name: "style"
                widget: "select"
                options: ["Default", "Numbered"]
              - label: FAQ
                name: faq
                widget: list
                fields:
                  - {label: Title, required: false, name: title, widget: string}
                  - {label: 'Body', required: false, name: 'body', widget: 'markdown'}


  # default blog posts collection
  # remove if your template does not support blog
  - name: 'blog_posts'
    label: 'Blog Posts'
    description: 'Add extra content to the site with blog posts related to your store and clients'
    folder: 'content/blog-posts'
    extension: 'json'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', required: false, name: 'layout', widget: 'hidden', default: 'blog'}
      - {label: 'Title', required: false, name: 'title', widget: 'string'}
      - {label: 'Publish Date', required: false, name: 'date', widget: 'datetime'}
      - {label: 'Featured Image', required: false, name: 'thumbnail', widget: 'image'}
      - {label: 'Short Description', required: false, name: 'description', widget: 'text'}
      - {label: 'Body', required: false, name: 'body', widget: 'markdown'}

  # default extra pages collection
  # eg.: 'about us', 'contact' and 'privacy'
  - name: 'extra_pages'
    label: 'Extra Pages'
    description: 'Add extra content to the site with blog posts related to your store and clients'
    folder: 'content/extra-pages'
    extension: 'json'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', required: false, name: 'layout', widget: 'hidden', default: 'blog'}
      - {label: 'Title', required: false, name: 'title', widget: 'string'}
      - {label: 'Publish Date', required: false, name: 'date', widget: 'datetime'}
      - {label: 'Featured Image', required: false, name: 'thumbnail', widget: 'image'}
      - {label: 'Short Description', required: false, name: 'description', widget: 'text'}
      - {label: 'Body', required: false, name: 'body', widget: 'markdown'}

  # general site settings
  # usually will be the same for any template
  - name: 'settings'
    label: 'Settings'
    description: 'General settings to modify the site identity and metadata'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'content/settings.json'
        fields:
          - {label: 'Name', name: 'name', widget: 'string'}
          - {label: 'Short Name', name: 'short_name', widget: 'string'}
          - {label: 'Short Description', name: 'description', widget: 'text'}
          - {label: 'Language', name: 'lang', widget: 'string'}
          - {label: 'Store ID', name: 'store_id', widget: 'number'}
          - {label: 'Store Object ID', name: 'store_object_id', widget: 'string'}
          - {label: 'Logo', name: 'logo', widget: 'image', required: false}
          - {label: 'Mini Logo', name: 'mini_logo', widget: 'image', required: false}
          - {label: 'Logo', required: false, name: 'logo', widget: 'image'}
          - {label: 'Primary Color', required: false, name: 'primary_color', widget: 'string'}
          - {label: 'Secondary Color', required: false, name: 'secondary_color', widget: 'string'}
          - {label: 'App Background Color', required: false, name: 'bg_color', widget: 'string'}
          - {label: 'Icon', required: false, name: 'icon', widget: 'image'}
          - {label: 'Large Icon', required: false, name: 'large_icon', widget: 'image'}
          - {label: 'Favicon', required: false, name: 'favicon', widget: 'image'}
  # Global header
  # It will be aplied at all pages asdasda
  - name: 'layout'
    label: 'Layout'
    description: 'Layout applied to all pages'
    delete: false
    editor:
      preview: false
    files:
      - name: 'footer'
        label: 'Footer'
        file: 'content/layout/footer.json'
        fields:
          - label: Descrição
            name: description
            widget: object
            fields:
              - {label: Título, hint: "Em destaque, dentro de uma tag H2", required: false, name: title, widget: string}
              - {label: Texto, required: false, name: body, widget: markdown}
          - label: Lista de links 1
            name: link_list_1
            widget: object
            hint: "Lista de links normalmente utilizada para exibir páginas como, Sobre nós e Política de privacidade"
            fields:
              - {label: Título, required: false, name: title, widget: string}
              - label: Links
                name: links
                widget: list
                fields:
                  - {label: Texto, required: false, name: text, widget: string}
                  - {label: URL, required: false, name: url, widget: string}
          - label: Lista de links 2
            name: link_list_2
            widget: object
            hint: "Lista adicional de links, para exibir páginas"
            fields:
              - {label: Título, required: false, name: title, widget: string}
              - label: Links
                name: links
                widget: list
                fields:
                  - {label: Texto, required: false, name: text, widget: string}
                  - {label: URL, required: false, name: url, widget: string}
          - label: Contatos
            name: contacts
            widget: object
            hint: "Contatos da loja"
            fields:
              - {label: Título, required: false, name: title, widget: string}
              - {label: Whatsapp, required: false, name: whatsapp, widget: string}
              - {label: Telefone, required: false, name: phone, widget: string}
              - {label: E-mail, required: false, name: e-mail, widget: string}
              - {label: 'Facebook', name: 'facebook', widget: 'string', required: false}
              - {label: 'Twitter', name: 'twitter', widget: 'string', required: false}
              - {label: 'Youtube', name: 'youtube', widget: 'string', required: false}
              - {label: 'Instagram', name: 'instagram', widget: 'string', required: false}
              - {label: 'Pinterest', name: 'pinterest', widget: 'string', required: false}
          - label: Selos
            name: seals
            widget: list
            fields:
              - {label: Imagem, required: false, name: image, widget: image}
              - {label: alt, required: false, name: Alt tag, widget: string}
          - label: Creditos
            name: credits
            widget: object
            fields:
              - {label: Texto, required: false, name: texto, widget: string}


      - name: 'header'
        label: 'Header'
        file: 'content/layout/header.json'
        fields:
          - label: "Tarja de marketing "
            name: "marketing_stripe"
            widget: object
            hint: "Tarja na cor secundária com texto e botão, caso não seja configurada não é exibida na loja"
            fields:
              - {label: 'Texto', name: 'text', required: false, widget: 'string'}
              - {label: 'Texto do botão', name: 'call_to_action', required: false, widget: 'string'}
              - {label: 'Link do botão', name: 'call_to_action_link', required: false, widget: 'string'}
          - label: "Tarja de contatos"
            name: "contacts_stripe"
            widget: object
            hint: "Tarja com contatos da loja, como páginas internas, telefones e redes sociais"
            fields:
              - label: Páginas
                name: pages
                widget: list
                fields:
                  - {label: Título, name: title, required: false, widget: string}
                  - {label: Link, name: link, required: false, widget: string}
              - {label: 'Telefone', name: 'phone', required: false, widget: 'string'}
              - {label: 'Whatsapp', name: 'whatsapp', required: false, widget: 'string'}
              - name: 'social_links'
                widget: object
                hint: "Entrar com a url da página nas devidas redes sociais"
                label: 'Links para redes sociais'
                fields:
                  - {label: 'Facebook', name: 'facebook', widget: 'string', required: false}
                  - {label: 'Twitter', name: 'twitter', widget: 'string', required: false}
                  - {label: 'Youtube', name: 'youtube', widget: 'string', required: false}
                  - {label: 'Instagram', name: 'instagram', widget: 'string', required: false}
                  - {label: 'Pinterest', name: 'pinterest', widget: 'string', required: false}
